package com.shareshow.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shareshow.aide.retrofit.entity.AmplyNotify;
import com.shareshow.aide.retrofit.entity.OrgAndDept;
import com.shareshow.aide.retrofit.entity.StudyMaterialsVisitingMaterials;
import com.shareshow.aide.retrofit.entity.TeamMorningData;
import com.shareshow.aide.retrofit.entity.VisitData;
import com.shareshow.db.AdFile;
import com.shareshow.db.AppUseInfo;
import com.shareshow.db.DevAdPlayRecord;
import com.shareshow.db.DevAreaUseInfo;
import com.shareshow.db.DeviceUser;
import com.shareshow.db.FileCordBean;
import com.shareshow.db.NotityBean;
import com.shareshow.db.ReadVisitTrackId;

import com.shareshow.db.AmplyNotifyDao;
import com.shareshow.db.OrgAndDeptDao;
import com.shareshow.db.StudyMaterialsVisitingMaterialsDao;
import com.shareshow.db.TeamMorningDataDao;
import com.shareshow.db.VisitDataDao;
import com.shareshow.db.AdFileDao;
import com.shareshow.db.AppUseInfoDao;
import com.shareshow.db.DevAdPlayRecordDao;
import com.shareshow.db.DevAreaUseInfoDao;
import com.shareshow.db.DeviceUserDao;
import com.shareshow.db.FileCordBeanDao;
import com.shareshow.db.NotityBeanDao;
import com.shareshow.db.ReadVisitTrackIdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig amplyNotifyDaoConfig;
    private final DaoConfig orgAndDeptDaoConfig;
    private final DaoConfig studyMaterialsVisitingMaterialsDaoConfig;
    private final DaoConfig teamMorningDataDaoConfig;
    private final DaoConfig visitDataDaoConfig;
    private final DaoConfig adFileDaoConfig;
    private final DaoConfig appUseInfoDaoConfig;
    private final DaoConfig devAdPlayRecordDaoConfig;
    private final DaoConfig devAreaUseInfoDaoConfig;
    private final DaoConfig deviceUserDaoConfig;
    private final DaoConfig fileCordBeanDaoConfig;
    private final DaoConfig notityBeanDaoConfig;
    private final DaoConfig readVisitTrackIdDaoConfig;

    private final AmplyNotifyDao amplyNotifyDao;
    private final OrgAndDeptDao orgAndDeptDao;
    private final StudyMaterialsVisitingMaterialsDao studyMaterialsVisitingMaterialsDao;
    private final TeamMorningDataDao teamMorningDataDao;
    private final VisitDataDao visitDataDao;
    private final AdFileDao adFileDao;
    private final AppUseInfoDao appUseInfoDao;
    private final DevAdPlayRecordDao devAdPlayRecordDao;
    private final DevAreaUseInfoDao devAreaUseInfoDao;
    private final DeviceUserDao deviceUserDao;
    private final FileCordBeanDao fileCordBeanDao;
    private final NotityBeanDao notityBeanDao;
    private final ReadVisitTrackIdDao readVisitTrackIdDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        amplyNotifyDaoConfig = daoConfigMap.get(AmplyNotifyDao.class).clone();
        amplyNotifyDaoConfig.initIdentityScope(type);

        orgAndDeptDaoConfig = daoConfigMap.get(OrgAndDeptDao.class).clone();
        orgAndDeptDaoConfig.initIdentityScope(type);

        studyMaterialsVisitingMaterialsDaoConfig = daoConfigMap.get(StudyMaterialsVisitingMaterialsDao.class).clone();
        studyMaterialsVisitingMaterialsDaoConfig.initIdentityScope(type);

        teamMorningDataDaoConfig = daoConfigMap.get(TeamMorningDataDao.class).clone();
        teamMorningDataDaoConfig.initIdentityScope(type);

        visitDataDaoConfig = daoConfigMap.get(VisitDataDao.class).clone();
        visitDataDaoConfig.initIdentityScope(type);

        adFileDaoConfig = daoConfigMap.get(AdFileDao.class).clone();
        adFileDaoConfig.initIdentityScope(type);

        appUseInfoDaoConfig = daoConfigMap.get(AppUseInfoDao.class).clone();
        appUseInfoDaoConfig.initIdentityScope(type);

        devAdPlayRecordDaoConfig = daoConfigMap.get(DevAdPlayRecordDao.class).clone();
        devAdPlayRecordDaoConfig.initIdentityScope(type);

        devAreaUseInfoDaoConfig = daoConfigMap.get(DevAreaUseInfoDao.class).clone();
        devAreaUseInfoDaoConfig.initIdentityScope(type);

        deviceUserDaoConfig = daoConfigMap.get(DeviceUserDao.class).clone();
        deviceUserDaoConfig.initIdentityScope(type);

        fileCordBeanDaoConfig = daoConfigMap.get(FileCordBeanDao.class).clone();
        fileCordBeanDaoConfig.initIdentityScope(type);

        notityBeanDaoConfig = daoConfigMap.get(NotityBeanDao.class).clone();
        notityBeanDaoConfig.initIdentityScope(type);

        readVisitTrackIdDaoConfig = daoConfigMap.get(ReadVisitTrackIdDao.class).clone();
        readVisitTrackIdDaoConfig.initIdentityScope(type);

        amplyNotifyDao = new AmplyNotifyDao(amplyNotifyDaoConfig, this);
        orgAndDeptDao = new OrgAndDeptDao(orgAndDeptDaoConfig, this);
        studyMaterialsVisitingMaterialsDao = new StudyMaterialsVisitingMaterialsDao(studyMaterialsVisitingMaterialsDaoConfig, this);
        teamMorningDataDao = new TeamMorningDataDao(teamMorningDataDaoConfig, this);
        visitDataDao = new VisitDataDao(visitDataDaoConfig, this);
        adFileDao = new AdFileDao(adFileDaoConfig, this);
        appUseInfoDao = new AppUseInfoDao(appUseInfoDaoConfig, this);
        devAdPlayRecordDao = new DevAdPlayRecordDao(devAdPlayRecordDaoConfig, this);
        devAreaUseInfoDao = new DevAreaUseInfoDao(devAreaUseInfoDaoConfig, this);
        deviceUserDao = new DeviceUserDao(deviceUserDaoConfig, this);
        fileCordBeanDao = new FileCordBeanDao(fileCordBeanDaoConfig, this);
        notityBeanDao = new NotityBeanDao(notityBeanDaoConfig, this);
        readVisitTrackIdDao = new ReadVisitTrackIdDao(readVisitTrackIdDaoConfig, this);

        registerDao(AmplyNotify.class, amplyNotifyDao);
        registerDao(OrgAndDept.class, orgAndDeptDao);
        registerDao(StudyMaterialsVisitingMaterials.class, studyMaterialsVisitingMaterialsDao);
        registerDao(TeamMorningData.class, teamMorningDataDao);
        registerDao(VisitData.class, visitDataDao);
        registerDao(AdFile.class, adFileDao);
        registerDao(AppUseInfo.class, appUseInfoDao);
        registerDao(DevAdPlayRecord.class, devAdPlayRecordDao);
        registerDao(DevAreaUseInfo.class, devAreaUseInfoDao);
        registerDao(DeviceUser.class, deviceUserDao);
        registerDao(FileCordBean.class, fileCordBeanDao);
        registerDao(NotityBean.class, notityBeanDao);
        registerDao(ReadVisitTrackId.class, readVisitTrackIdDao);
    }
    
    public void clear() {
        amplyNotifyDaoConfig.clearIdentityScope();
        orgAndDeptDaoConfig.clearIdentityScope();
        studyMaterialsVisitingMaterialsDaoConfig.clearIdentityScope();
        teamMorningDataDaoConfig.clearIdentityScope();
        visitDataDaoConfig.clearIdentityScope();
        adFileDaoConfig.clearIdentityScope();
        appUseInfoDaoConfig.clearIdentityScope();
        devAdPlayRecordDaoConfig.clearIdentityScope();
        devAreaUseInfoDaoConfig.clearIdentityScope();
        deviceUserDaoConfig.clearIdentityScope();
        fileCordBeanDaoConfig.clearIdentityScope();
        notityBeanDaoConfig.clearIdentityScope();
        readVisitTrackIdDaoConfig.clearIdentityScope();
    }

    public AmplyNotifyDao getAmplyNotifyDao() {
        return amplyNotifyDao;
    }

    public OrgAndDeptDao getOrgAndDeptDao() {
        return orgAndDeptDao;
    }

    public StudyMaterialsVisitingMaterialsDao getStudyMaterialsVisitingMaterialsDao() {
        return studyMaterialsVisitingMaterialsDao;
    }

    public TeamMorningDataDao getTeamMorningDataDao() {
        return teamMorningDataDao;
    }

    public VisitDataDao getVisitDataDao() {
        return visitDataDao;
    }

    public AdFileDao getAdFileDao() {
        return adFileDao;
    }

    public AppUseInfoDao getAppUseInfoDao() {
        return appUseInfoDao;
    }

    public DevAdPlayRecordDao getDevAdPlayRecordDao() {
        return devAdPlayRecordDao;
    }

    public DevAreaUseInfoDao getDevAreaUseInfoDao() {
        return devAreaUseInfoDao;
    }

    public DeviceUserDao getDeviceUserDao() {
        return deviceUserDao;
    }

    public FileCordBeanDao getFileCordBeanDao() {
        return fileCordBeanDao;
    }

    public NotityBeanDao getNotityBeanDao() {
        return notityBeanDao;
    }

    public ReadVisitTrackIdDao getReadVisitTrackIdDao() {
        return readVisitTrackIdDao;
    }

}
