package com.shareshow.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "READ_VISIT_TRACK_ID".
*/
public class ReadVisitTrackIdDao extends AbstractDao<ReadVisitTrackId, Void> {

    public static final String TABLENAME = "READ_VISIT_TRACK_ID";

    /**
     * Properties of entity ReadVisitTrackId.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property VisitId = new Property(0, String.class, "visitId", false, "VISIT_ID");
    }


    public ReadVisitTrackIdDao(DaoConfig config) {
        super(config);
    }
    
    public ReadVisitTrackIdDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"READ_VISIT_TRACK_ID\" (" + //
                "\"VISIT_ID\" TEXT);"); // 0: visitId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"READ_VISIT_TRACK_ID\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReadVisitTrackId entity) {
        stmt.clearBindings();
 
        String visitId = entity.getVisitId();
        if (visitId != null) {
            stmt.bindString(1, visitId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReadVisitTrackId entity) {
        stmt.clearBindings();
 
        String visitId = entity.getVisitId();
        if (visitId != null) {
            stmt.bindString(1, visitId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ReadVisitTrackId readEntity(Cursor cursor, int offset) {
        ReadVisitTrackId entity = new ReadVisitTrackId( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // visitId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReadVisitTrackId entity, int offset) {
        entity.setVisitId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ReadVisitTrackId entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ReadVisitTrackId entity) {
        return null;
    }

    @Override
    public boolean hasKey(ReadVisitTrackId entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
